name: 🐛 Bug Report
description: バグレポート用テンプレート
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: バグの説明
      description: 何が起きているかを説明
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: バグを再現する手順
      placeholder: |
        1. ...
        2. ...
        3. ...