name: Claude Code Action

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

# 同一Issueでの重複実行を防止 (Gemini推奨)
concurrency:
  group: ${{ github.repository }}-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  claude:
    if: |
      github.event.sender.type != 'Bot' && (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
      )
    runs-on: ubuntu-latest
    
    # 必要最小限の権限設定 (Gemini推奨)
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Claude Code Action
      uses: anthropics/claude-code-action@beta
      with:
        claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    # Slack通知ステップ
    - name: Notify Slack on success
      if: success()
      run: |
        curl -X POST -H "Content-type: application/json" \
          --data '{"text":"✅ ずんだもん:Claude Code Actionが成功したのだ！！"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
          
    - name: Notify Slack on failure  
      if: failure()
      run: |
        curl -X POST -H "Content-type: application/json" \
          --data '{"text":"❌ ずんだもん:Claude Code Actionが失敗したのだ..."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}