  name: Claude Code Action

  on:
    issue_comment:
      types: [created]

  jobs:
    claude:
      if: github.event.sender.type != 'Bot' && contains(github.event.comment.body, '@claude')
      runs-on: ubuntu-latest

      steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
